### ISSUE TITLE
PCB does not show polarity of buzzer

### ISSUE THREAD

**Issue by ursminor** [sparkfun/Binary_Blaster#1]

**Comment by bboyho** [comment]
Hi,

Thank you for the feedback. I just saw your issue. The buzzer has a polarity marker but it should not matter when soldered on the board. The buzzer will still function regardless of the orientation. Checking with the engineer, we do not believe that this is a significant issue to warrant a revision. If you would like to follow along with the [assembly guide](https://learn.sparkfun.com/tutorials/binary-blaster-assembly-guide#buzzer-and-switches) feel free to insert the buzzer into the PCB by having the "+" close to the "BIT 0" silkscreen as indicated in the image.

If you happen to solder the buzzer differently but wanted to follow the guide, you can rework the board by heating both through holes with your soldering iron and carefully remove the component from the through hole. Using a solder sucker or the [slap method](https://www.sparkfun.com/tutorials/339), remove any remaining solder on the PTH pads. After removing any excess solder from the pins, insert buzzer back into through holes with the orientation based on the guide before soldering the pins again. When reworking PTH components, there is a risk of pulling pads so make sure to fully heat the solder joints!
